### DISCUSSION TITLE
UvDesk Mail Configuration Issues

### DISCUSSION THREAD

**Discussion by 5thDimensionalVader** [uvdesk/community-skeleton#701] [General]
Hello Team,

I recently installed UvDesk (by downloading the project) and navigating to https://project_folder/public to complete installation. It installed successfully but I am unable to get the mail configured to receive and send emails.

I followed the installation instructions closely but it didn't resolve the issue. Below are the yaml configuration files in /config/packages/:

## swiftmailer.yaml
```
swiftmailer:
    default_mailer: mailer_1699
    mailers:
        mailer_1699:
            transport: smtp
            username: support
            password: XXXXXXXXXX
            host: mail.server.com
            port: 587
            encryption: tls
            auth_mode: login
            sender_address: support@domain.net
            delivery_addresses: ['support@domain.net']
            disable_delivery: false
```

## uvdesk.yaml

```
parameters:
    app_locales: en|fr|it|de|da|ar|es|tr|zh|pl
    
    # Default Assets
    assets_default_agent_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png'
    assets_default_customer_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png'
    assets_default_helpdesk_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png'

    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer

    # File uploads constraints
    # @TODO: Set these parameters via compilers
    max_post_size: 8388608
    max_file_uploads: 20
    upload_max_filesize: 2097152

uvdesk:
    site_url: support.domain.net/public
    upload_manager:
        id: Webkul\UVDesk\CoreFrameworkBundle\FileSystem\UploadManagers\Localhost
    
    support_email:
        id: support@domain.net
        name: ExRx Support
        mailer_id: mailer_1699
    
    # Default resources
    default:
        ticket:
            type: support
            status: open
            priority: low
        templates:
            email: mail.html.twig
```

## uvdesk_mailbox.yaml

```
uvdesk_mailbox:
    emails: ~
        # Often Reply emails like from gmail contains extra and redundant previous mail data.
        # This data can be removed by adding delimiter i.e. specific line before each reply. 
        # delimiter: '<-- Please add content above this line -->'
        # enable_delimiter: true
    
    # Configure your mailboxes here
    mailboxes:
        support@domain.net:
            name: Support
            enabled: true
            deleted: false

            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server: 
                mailer_id: mailer_1699

            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: '{main.server.com:993/imap/ssl}INBOX'
                username: support
                password:  XXXXXXXXXX
```
                
When testing the IMAP configuration to fetch mails, I got a "Connection Refused" error (see screenshot below):
![imap_error](https://github.com/uvdesk/community-skeleton/assets/61785143/fc63205c-b464-486f-9886-463c192ed55d)

I am hoping I can find a solution to get this resolved as this issue has delayed me a lot.

Thank you for your time!
