### DISCUSSION TITLE
UVDesk with php-fpm + nginx in Docker

### DISCUSSION THREAD

**Discussion by tbfpartner** [uvdesk/community-skeleton#808] [Show and tell]
_First off... i did this just as a test - hence it is still running as root (which is not best practice of course!)_

I have changed the way this software is deployed through docker. Instead of using the existing _Dockerfile_ & configs, I opted in for php-fpm + nginx. The whole software runs as a docker stack with multiple containers (one for each microservice: php-fpm, nginx, mariadb). 

It also uses a new logic for setup, as mentioned in this PR: https://github.com/uvdesk/community-skeleton/pull/807

### Files

[docker.zip](https://github.com/user-attachments/files/19210964/docker.zip)

- The `nginx.conf.template` contains the webserver config with a variable
- The `nginx.entrypoint.sh` take that template and substitutes the variable - nothing else
- The `php.ini` just contains what the current projects `php.ini` contains -> _memory_limit=1024M_
- The `php.entrypoint.sh` basically just runs the new command `php bin/console uvdesk:configure-helpdesk -n` to automatically setup UVDesk.
- The `Dockerfile` is a two-step build, first building a php container, then a nginx container. It installs all necessary software, copies the source, (runs php composer) and sets up the entrypoints.

### Logic

_I use Docker Swarm + Traefik Reverse Proxy. Adjust certain parts accordingly!_
After the successful build, i use a docker-compose.yml to instruct docker, how to start the container stack.
```
networks:
  backend:
    driver: overlay
  public:
    external: true
services:
  webserver:
    image: {PATH-TO-REGISTRY}/nginx:latest
    environment:
      WORKER_HOST: worker
    networks:
      - public
      - backend
    depends_on:
      - worker
    deploy:
      labels:
        - "traefik.enable=true"
        - {more traefik stuff}
  worker:
    image: {PATH-TO-REGISTRY}/php:latest
    environment:
      APP_ENV: prod
      APP_URL: {https://change.me}
      APP_TIMEZONE: 'Europe/Berlin'
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: uvdesk
      DB_PASSWORD: uvdesk
      DB_DATABASE: uvdesk
      DATABASE_URL: mysql://uvdesk:uvdesk@mariadb:3306/uvdesk
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: test@test.te
      SUPERUSER_PASSWORD: TestAdmin123.
    networks:
      - backend
    depends_on:
      - mariadb        
  mariadb:
    image: mariadb:latest@sha256:bfb1298c06cd15f446f1c59600b3a856dae861705d1a2bd2a00edbd6c74ba748 # 11.6.2
    environment:
      MARIADB_USER: uvdesk
      MARIADB_PASSWORD: uvdesk
      MARIADB_DATABASE: uvdesk
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - /path/to/persistant/data:/var/lib/mysql
    networks:
      - backend

```
