### DISCUSSION TITLE
Swift Mailer / SMTP Issue

### DISCUSSION THREAD

**Discussion by MrRamyg** [uvdesk/community-skeleton#814] [Q&A] [answered]
Hello,

I recently installed UVdesk, but I'm encountering an issue with Swift Mailer and SMTP on my setup. I've gone through the documentation and searched for similar discussions but haven't found a solution yet.

Issue details:

SMTP server: mail.nexarisds.org

Error message: There aren't really any errors other than a warning when replying to a ticket, which shows a success message, but also says 1 Swift Mailer is not working.

PHP version: 8.2.28

Configuration: 
                                                         
```
swiftmailer:
    default_mailer: support@nexarisds.org
    mailers:
        support@nexarisds.org:
            transport: smtp
            username: support@nexarisds.org
            password: "somepasswordhere"
            host: mail.nexarisds.org
            port: 587
            encryption: tls
            auth_mode: login
            sender_address: support@nexarisds.org
            delivery_addresses: ['']
            disable_delivery: false
            stream_options:
                ssl:
                    verify_pear: false
                    verify_pear_name: false

```

I've verified that my SMTP credentials are correct, but the issue persists. When resetting password, that works, sending an email manually also works, but doing so via the dashboard, etc, doesn't. Any help or advice here? 😁

Thanks in advance!
