### ISSUE TITLE
Swift mailer and Email settings configuration for Mailgun not working

### ISSUE THREAD

**Issue by kifurax-react** [uvdesk/community-skeleton#208]
**Description**  
Hi all,

I am trying to configure the open source version of UV desk to send, receive and also convert mails from Mailgun to tickets. I feel I got the configuration right but Mail not received to customer/agent of below reply

Below are configuration files. Please advise if I entered the correct values. I would any help or insight.

**How to reproduce**  
swiftmailer.yam config
`swiftmailer:
    default_mailer: mailer_5177
    mailers:
        mailer_5177:
            transport: smtp
            username: support@blog.Mymailgundomain.com
            password: MyPassword
            host: smtp.eu.mailgun.org
            port: 587
            encryption: tls
            auth_mode: login
            sender_address: support@mydomain.com
            delivery_addresses: ['support@blog.Mymailgundomain.com']
            disable_delivery: false`

uvdesk_mailbox.yaml:

```
uvdesk_mailbox:
    emails: ~
        # Often Reply emails like from gmail contains extra and redundant previous mail data.
        # This data can be removed by adding delimiter i.e. specific line before each reply. 
        # delimiter: '<-- Please add content above this line -->'
        # enable_delimiter: true
    
    # Configure your mailboxes here
    mailboxes:
        mailbox_1151:
            name: Support 
            enabled: true

            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server: 
                mailer_id: mailer_5177

            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: 'mail.livemail.co.uk'
                username: support@mydomain.com
                password: mypassword
```

**Possible Solution**  

**Additional context**  

If someone as a suggestion or i should use Gmail?
Thanks
