### ISSUE TITLE
Prod.log file not found in production mode

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/community-skeleton#517]
# Bug report
Prod.log file not found in production mode

### Issue Description

If the user runs the project in prod mode so not create a **prod.log file** in this path:
var/log/prod.log 

### Steps to reproduce
Step 1: Your project change environment mode: dev to prod mode
Step 2: Now go to your project directory and check in this file root **var/log/prod.log** file not to create

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

I am also able to reproduce this issue & also fixed this issue by setup the path in a monolog.yaml inside prod folder.

config/packages/prod/monolog.yaml
```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```
