### ISSUE TITLE
container not being up with a persistent config in docker-compose.yml exit code 1

### ISSUE THREAD

**Issue by Cronist** [uvdesk/community-skeleton#597]
I am following up here:

https://github.com/uvdesk/community-skeleton/wiki/dockerize-helpdesk-project

I downloaded the zip file. extracted on my ubuntu server. compiles with the command below.

`docker build -t uvdesk:latest .`

run the container with CLI below

`docker run -dit -p 8888:80  -e MYSQL_USER=uvdesk     -e MYSQL_ROOT_PASSWORD=rootpassword     -e MYSQL_PASSWORD=uvdeskpwd     -e MYSQL_DATABASE=uvdesk     --name uvdesk uvdesk`

it runs without problem. 

But when the container is down and restarts, all configs have gone as expected. so I tried to create a persistent data storage for SQL data, ticket attachments, and server-side uploads like logos, etc.

```
version: '3'

services:
  uvdesk:
    image: uvdesk:latest
    tty: true
    environment:
      MYSQL_USER: uvdesk
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: uvdeskpwd
      MYSQL_DATABASE: uvdesk
	network_mode: "host"
    ports:
      - 8888:80
    volumes:
      - sql_data:/var/lib/mysql:rw
      - web_data:/var/www/uvdesk/public/assets/website:rw
      - ticket_data:/var/www/uvdesk/public/attachments:rw

volumes:   
 sql_data:
   driver: local
   driver_opts:
    type: none
    device: $PWD/sql-data
    o: bind
 web_data:
  driver: local
  driver_opts:
   type: none
   device: $PWD/web-data
   o: bind
 ticket_data:
  driver: local
  driver_opts:
   type: none
   device: $PWD/ticket-data
   o: bind
```

The directory structure is like this:

docker-compose.yml  
sql-data  
ticket-data  
web-data

```
$ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use docker stack deploy.

Recreating doc_uvdesk_1 ... done
Attaching to doc_uvdesk_1
uvdesk_1  |  * Restarting Apache httpd web server apache2                       AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.1.80. Set the 'ServerName' directive globally to suppress this message
uvdesk_1  |                                                              [ OK ]
uvdesk_1  |  * Stopping MySQL database server mysqld                     [ OK ] 
uvdesk_1  |  * Starting MySQL database server mysqld                            No directory, logging in with HOME=/
uvdesk_1  |                                                              [ OK ]
uvdesk_1  | mysqladmin: connect to server at 'localhost' failed
uvdesk_1  | error: 'Access denied for user 'root'@'localhost' (using password: NO)'
uvdesk_1  | Error: Failed to establish a connection with mysql server (localhost)
uvdesk_1  | 
doc_uvdesk_1 exited with code 1
$
```
