### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by tperrindell** [uvdesk/community-skeleton#624]
# Bug report

### Title
After deploying a docker-compose with uvdesk installed in Dockerfile custom image, the installer fails to connect to database

### Issue Description
I created a Dockerfile to deploy uvdesk using composer : 
```
FROM php:7-apache
# Let's use something already well documented

# User variables
## Proxy if needed
ARG HTTP_PROXY=http://myproxy:80
ARG HTTPS_PROXY=http://myproxy:80
# Composer Mem limit for the build
ARG COMPOSER_MEMORY_LIMIT=-1
# Timezone
ENV TZ=Europe/Paris

# Let's make sure we don't get prompted when installing packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Adding manual proxy to apt as variables are not used
RUN echo 'Acquire { \
  HTTP::proxy "http://myproxy:80";\
  HTTPS::proxy "http://myproxy:80";\
}' > /etc/apt/apt.conf.d/99-proxy.conf

# Add uvdesk user
RUN adduser uvdesk -q --disabled-password --gecos ""

# Install packages
RUN apt-get update && apt-get -y install apt-utils git unzip

# Use easy php extensions installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Setup yet another proxy
RUN pear config-set http_proxy ${HTTP_PROXY}

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions zip curl imap mailparse mysqli

WORKDIR /var/www
# Download & Install composer
ADD https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer /tmp/composer-installer.php
RUN     cd /var/www && \
        php /tmp/composer-installer.php

#Install uvdesk through composer
RUN ./composer.phar create-project uvdesk/community-skeleton /var/www/uvdesk

# Add your env file
ADD env /var/www/uvdesk/.env

# Let's copy the apache2 config
RUN cp /var/www/uvdesk/.docker/config/apache2/vhost.conf /etc/apache2/sites-available/000-default.conf && \
        cp /var/www/uvdesk/.docker/config/apache2/httpd.conf /etc/apache2/apache2.conf &&\
        cp /var/www/uvdesk/.docker/config/apache2/env /etc/apache2/envvars

# Make uvdesk owner of the folder
RUN chown -R uvdesk:uvdesk /var/www/uvdesk

# Enable rewrite mod
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
```

Which I then deploy using the following docker-compose (some info retracted of course):
```
version: '3.3'

services:
  uvdesk-app:
    build: build
    tty: true
    restart: always
    container_name: uvdesk-app
    networks:
      - traefik
      - uvdesk
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uvdesk.rule=Host(`uvdesk.mydomain.com`)"
      - "traefik.http.routers.uvdesk.entrypoints=web,websecure"
      - "traefik.http.routers.uvdesk.tls=true"
      - "traefik.http.services.uvdesk.loadbalancer.server.port=80"

  uvdesk-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: uvdesk-db
    environment:
      - TZ=Europe/Paris
      - PUID=1109
      - PGID=1110
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_PASSWORD=yyy
      - MYSQL_USER=uvdeskuser
      - MYSQL_DATABASE=uvdesk
    restart: unless-stopped
    volumes:
      - /opt/docker/data/uvdesk/uvdesk-db-data:/config
    networks:
      - uvdesk
networks:
  uvdesk:
  traefik:
    external: true
```

### Steps to reproduce
1. Copy docker file & compose as above
2. Launch the environment using docker-compose up -d
3.  Run the wizard

### Expected result
Connection to DB should work fine and setup should go through 

### Actual result

Connection to DB fails with the error : 
Details are incorrect ! Connection not established.
https://i.imgur.com/5dIZuld.png
I tried using uvdeskuser & root, both result as failed.

When trying to connect manually from the container, it works: 
```
# docker exec -it uvdesk-app mysql -h uvdesk-db -u uvdeskuser -p -e "show databases;"
Enter password: yyy
+--------------------+
| Database           |
+--------------------+
| information_schema |
| uvdesk             |
+--------------------+
```

I don't know how to enable debug log.

Please advise :)

**Comment by Komal-sharma-2712** [comment]
@tperrindell 
Once we will review it and update you.

**Comment by tperrindell** [comment]
If you're not using a proxy, then remove the RUN echo acquire part and the proxy lines, otherwise it might not work :)

**Comment by Firesphere** [comment]
I just encountered exactly the same problem.
No matter what, exposing the db through the host, using a custom IP assignment, nothing will make the connection "work", even though all manual attempts to connect to the database, even over an SSH tunnel, work just fine.

**Comment by tperrindell** [comment]
> @tperrindell Once we will review it and update you.

Hello ! 

Any update?

Thanks

**Comment by tperrindell** [comment]
Hi, any ideas on what the problem could be?

**Comment by tperrindell** [comment]
Hello, 

a quick update would be nice !

**Comment by akshaywebkul** [comment]
Hello @tperrindell & @Firesphere,

So I looked into the provided docker compose configurations to review these issues accordingly. There are a few things to note:
- In your _Dockerfile_, that there was no _pdo_mysql_ driver extension installed required for communicating with your database server.
- We also further need to specify the database server version being used in this case where you are using MariaDB instead of MySQL, otherwise the wizard tries to establish a connection presuming that we're connecting to a MySQL database. I've added a new commit to [branch 1.1](https://github.com/uvdesk/community-skeleton/tree/1.1) which addresses this issue.
- I also noticed that in the created MariaDB container, the provided credentials in the docker-compose where not used, and instead i had to login to the mariadb session using root.

Following along, I made a few changes to the _Dockerfile_ & _docker-compose.yaml_ but you should be able to follow it along and adapt it to your specific use case:

**Dockerfile**:

```
# ./build/Dockerfile
FROM php:7-apache

ARG COMPOSER_MEMORY_LIMIT=-1

# Let's make sure we don't get prompted when installing packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Add uvdesk user
RUN adduser uvdesk -q --disabled-password --gecos ""

# Install packages
RUN apt-get update && apt-get -y install wget git unzip zip curl nano;

# Install PHP extensions installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# Install PHP extensions
RUN install-php-extensions imap mailparse mysqli pdo_mysql

# Copy necessary apache & php configuration files
COPY ./.docker/config/apache2/env /etc/apache2/envvars
COPY ./.docker/config/apache2/httpd.conf /etc/apache2/apache2.conf
COPY ./.docker/config/apache2/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY ./.docker/config/php/php.ini /usr/local/etc/php/php.ini

RUN \
    # Update apache configurations
    a2enmod php7.4 rewrite; \
    # Download and verify composer installer signature
    wget -O /usr/local/bin/composer.php "https://getcomposer.org/installer"; \
    actualSig="$(wget -q -O - https://composer.github.io/installer.sig)"; \
    currentSig="$(shasum -a 384 /usr/local/bin/composer.php | awk '{print $1}')"; \
    if [ "$currentSig" != "$actualSig" ]; then \
        echo "Warning: Failed to verify composer signature."; \
        exit 1; \
	fi; \
    # Install composer
    php /usr/local/bin/composer.php --install-dir=/usr/local/bin --filename=composer \
    && chmod +x /usr/local/bin/composer;

# Clean up files
RUN \
    rm -rf \
        /var/www/html \
        /usr/local/bin/composer.php;

RUN usermod -aG uvdesk root && usermod -aG uvdesk www-data;
RUN chown -R uvdesk:uvdesk /var/www;

WORKDIR /var/www
```
**docker-compose.yaml**:

```
# ./docker-compose.yaml
version: '3.3'

services:
    uvdesk-app:
        build: build
        tty: true
        restart: always
        container_name: uvdesk-app
        ports:
            - '8082:80'
        networks:
            - uvdesk
        depends_on:
            - uvdesk_db
        links:
            - uvdesk_db

    uvdesk_db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: rootpassword
        container_name: uvdesk_db
        networks:
            - uvdesk

networks:
    uvdesk:
        external: true
```

**Instructions**:

1. Re-build your images and initialize your docker containers using the following command:

    `$ docker-compose up -d`

2. Once your containers are up & running, use the following command to interact with the shell interface of your container:

    `$ docker exec -it uvdesk-app bash`

3. Once you're withing your container's shell, use the following command to switch to the uvdesk user instead of root:

    `$ su uvdesk`

4. Create the helpdesk project using the following command:

    `$ composer create-project uvdesk/community-skeleton:1.1.x-dev uvdesk`

5. Use the following command to download [Adminer.php](https://www.adminer.org/) to interact with your database:

    `$ wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-en.php -O ./uvdesk/public/adminer.php`

Navigate to http://localhost:8082 in your browser, where you'll be present with the installation wizard, follow along with the instructions provided and your helpdesk should be installed without any issues.

If you want to know which database version you're using, navigate to http://localhost:8082/adminer.php and login to your database using the configured credentials and you'll be able to see your exact database version. You can specify this version detail during the installation process.

Hope this helps resolves your issues!

Reference screenshots:

![Screenshot from 2022-12-20 17-20-09](https://user-images.githubusercontent.com/29193211/208660934-17881718-2fc5-4d7b-8e8e-25a99123c42a.png)
![Screenshot from 2022-12-20 17-20-57](https://user-images.githubusercontent.com/29193211/208660982-f6fecfb8-0aa3-41e7-b923-14212cb671ba.png)
![Screenshot from 2022-12-20 17-24-18](https://user-images.githubusercontent.com/29193211/208661249-928a4ff9-bc70-4ec2-9abc-6d4b78ca60d7.png)

**Comment by tperrindell** [comment]
Thanks, I'll try it out.

FYI the reason I didn't use pdo is because mysqli was present and can be used to connect to mariadb, as it is a mysql fork.

I moved the db container to a mysql one to try it out, I will post the results after testing.

**Comment by tperrindell** [comment]
OK So it moves a step further, but I still have an issue : 
![image](https://user-images.githubusercontent.com/103429802/208686775-31e6dcd9-5778-48e7-9bad-88114d6f09d4.png)

All checks are green, I can go past the SQL connection step, and then: 
![image](https://user-images.githubusercontent.com/103429802/208687032-91c18631-c62a-446b-865c-ee44eb4ff07e.png)

If I check in the container : 
```
uvdesk@eb44412b75bf:~$ ls -l /var/www/uvdesk/.env
-rwxrwxr-x. 1 uvdesk uvdesk 521 Dec 20 13:54 /var/www/uvdesk/.env
```

I'll let it run, but I'm not sure if it's doing anything.
The last entry in the logs looks like this:

```
uvdesk-app  | 172.19.0.5 - - [20/Dec/2022:15:13:24 +0100] "POST /wizard/xhr/load/configurations HTTP/1.1" 500 355 "https://uvdesk.xxx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by tperrindell** [comment]
Docker compose is modified to use mysql:
```
version: '3.3'

services:
  uvdesk-app:
    build: build
    tty: true
    restart: always
    container_name: uvdesk-app
    networks:
      - traefik
      - uvdesk
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uvdesk.rule=Host(`uvdesk.mydomain.com`)"
      - "traefik.http.routers.uvdesk.entrypoints=web,websecure"
      - "traefik.http.routers.uvdesk.tls=true"
      - "traefik.http.services.uvdesk.loadbalancer.server.port=80"

  uvdesk-db:
    image: mysql:latest
    container_name: uvdesk-db
    environment:
      - TZ=Europe/Paris
      - PUID=1109
      - PGID=1110
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_PASSWORD=yyy
      - MYSQL_USER=uvdeskuser
      - MYSQL_DATABASE=uvdesk
    restart: unless-stopped
    volumes:
      - /opt/docker/data/uvdesk/uvdesk-db-data:/var/lib/mysql/
    networks:
      - uvdesk
networks:
  uvdesk:
  traefik:
    external: true
```

New dockerfile:
```
FROM php:7-apache
# Let's use something already well documented

# User variables
## Proxy if needed
ARG HTTP_PROXY=http://myproxy:80
ARG HTTPS_PROXY=http://myproxy:80
# Composer Mem limit for the build
ARG COMPOSER_MEMORY_LIMIT=-1
# Timezone
ENV TZ=Europe/Paris

# Let's make sure we don't get prompted when installing packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Adding manual proxy to apt as variables are not used
RUN echo 'Acquire { \
  HTTP::proxy "http://myproxy:80";\
  HTTPS::proxy "http://myproxy:80";\
}' > /etc/apt/apt.conf.d/99-proxy.conf

# Add uvdesk user
RUN adduser uvdesk -q --disabled-password --gecos ""

# Install packages
RUN apt-get update && apt-get -y install apt-utils git unzip curl

# Use easy php extensions installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Setup yet another proxy
RUN pear config-set http_proxy ${HTTP_PROXY}

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions zip curl imap mailparse mysqli pdo_mysql

WORKDIR /var/www
# Download & Install composer
ADD https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer /tmp/composer-installer.php
RUN     cd /var/www && \
        php /tmp/composer-installer.php

#Install uvdesk through composer
RUN ./composer.phar create-project uvdesk/community-skeleton /var/www/uvdesk
ADD https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-en.php /var/www/uvdesk/public/adminer.php

# Add your env file
ADD env /var/www/uvdesk/.env
RUN chmod 775 /var/www/uvdesk/.env

# Let's copy the apache2 config
RUN cp /var/www/uvdesk/.docker/config/apache2/vhost.conf /etc/apache2/sites-available/000-default.conf && \
        cp /var/www/uvdesk/.docker/config/apache2/httpd.conf /etc/apache2/apache2.conf &&\
        cp /var/www/uvdesk/.docker/config/apache2/env /etc/apache2/envvars

# Make uvdesk owner of the folder
RUN chown -R uvdesk:uvdesk /var/www/uvdesk

# Enable rewrite mod
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
```

Adminer shows that I can login with my uvdeskuser & password : 
![image](https://user-images.githubusercontent.com/103429802/208688048-07dbdc96-db22-4b82-8319-bc1766f929a2.png)
