### ISSUE TITLE
API Attempted to call an undefined method named generateCompleteLocalResourcePathUri

### ISSUE THREAD

**Issue by Gybrush6521** [uvdesk/community-skeleton#784]
**Description**  
I tried to get all tickets with the api call  /api/v1/tickets and I get the error message: 
```
{"status":false,"message":"Attempted to call an undefined method named \u0022generateCompleteLocalResourcePathUri\u0022 of class \u0022Webkul\\UVDesk\\CoreFrameworkBundle\\Services\\UVDeskService\u0022."}* shutting down connection #0
* schannel: shutting down SSL/TLS connection with XXXXXXXX port 443
```

**How to reproduce**  
`curl -X GET -H "Authorization: Basic XXXXXX" "https://XXXXXX/api/v1/tickets"`

**Additional context**  
API installed with these commands:
```
composer require uvdesk/api-bundle""
php bin/console doctrine:schema:update --force
php bin/console cache:clear --env dev
```
Then modified security.yaml
```
    encoders:
        Webkul\UVDesk\CoreFrameworkBundle\Entity\User: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            id: user.provider
        uv_api_credentials:
            id: Webkul\UVDesk\ApiBundle\Providers\ApiCredentials

    firewalls:
```

```
                target: helpdesk_member_handle_login
        uvdesk_api:
            pattern: ^/api
            anonymous: true
            provider: uv_api_credentials
            guard:
                authenticators:
                    Webkul\UVDesk\ApiBundle\Security\Guards\APIGuard: Webkul\UVDesk\ApiBundle\Security\Guards\APIGuard
        customer:
```
Then created API token in the uvdesk Admin Webinterface

I am using the dev version 1.2 (to work with MS365 Mailboxes)
