### ISSUE TITLE
Warning: imap_open(): Couldn't open stream ssl0.ovh.net

### ISSUE THREAD

**Issue by Nonolanlan1007** [uvdesk/community-skeleton#796]
I have uvdesk almost fully configured. I tested it by sending an email to support@company.com and nothing happened. I have logged in to the mailbox using Thunderbird and the exact same credentials that I gave UVDesk. 
I saw in this repository that it was possible to force the mailbox to refresh with the `php bind/console uvdesk:refresh-mailbox support@company.com` and I got the following error:
```
 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream... 

In RefreshMailboxCommand.php line 88:
                                                           
  Warning: imap_open(): Couldn't open stream ssl0.ovh.net  
                                                           

uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: Can't open mailbox ssl0.ovh.net: no such mailbox (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler->handleError(8, 'Unknown: Can't ...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0
PHP Stack trace:
PHP   1. {main}() /var/www/uvdesk/bin/console:0
PHP   2. Symfony\Component\Console\Application->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'uvdesk:refresh-mailbox', 1 => 'support@boardstack.app']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'uvdesk:refresh-mailbox', 'emails' => [...]]; protected $interactive = TRUE }, $output = *uninitialized*) /var/www/uvdesk/bin/console:42
```

Here is my `uvdesk_mailbox.yaml`:
```
uvdesk_mailbox:
    emails: ~
        # Often Reply emails like from gmail contains extra and redundant previous mail data.
        # This data can be removed by adding delimiter i.e. specific line before each reply. 
        # delimiter: '<-- Please add content above this line -->'
        # enable_delimiter: true
    
    # Configure your mailboxes here
    mailboxes:
        mailbox_4111:
            name: Company Support
            enabled: true
            deleted: true

            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server: 
                mailer_id: mailer_1548

            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: 'ssl0.ovh.net'
                username: support@company.net
                password: ************
```

Kind Regards
